-- MySQL Script generated by MySQL Workbench
-- 11/05/16 16:24:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schmal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schmal
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `schmal` DEFAULT CHARACTER SET utf8 ;
-- USE `schmal` ;

-- -----------------------------------------------------
-- Table `schmal`.`applicant_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`applicant_level` (
  `applicant_level_id` INT(11) NOT NULL,
  `applicant_level` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`applicant_level_id`),
  UNIQUE INDEX `applicant_level_UNIQUE` (`applicant_level` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`user_group` (
  `user_group_id` BIGINT(20) NOT NULL,
  `user_group_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_group_id`),
  UNIQUE INDEX `user_group_name_UNIQUE` (`user_group_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`access` (
  `access_id` BIGINT(20) NOT NULL,
  `description` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`access_id`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`user` (
  `user_id` BIGINT(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `prename` MEDIUMTEXT NOT NULL,
  `surname` MEDIUMTEXT NOT NULL,
  `email` MEDIUMTEXT NOT NULL,
  `phone` MEDIUMTEXT NOT NULL,
  `token` MEDIUMTEXT NOT NULL,
  `login_time` DATE NOT NULL,
  `last_login` DATE NOT NULL,
  `user_group_id` BIGINT(20) NOT NULL,
  `access_id` BIGINT(20) NOT NULL,
  `voting_reminder` CHAR(1) NOT NULL,
  `new_applicants_reminder` CHAR(1) NOT NULL,
  PRIMARY KEY (`user_id`, `user_group_id`, `access_id`),
  INDEX `user_group_id_idx` (`user_group_id` ASC),
  INDEX `access_id_idx` (`access_id` ASC),
  CONSTRAINT `user_user_group`
    FOREIGN KEY (`user_group_id`)
    REFERENCES `schmal`.`user_group` (`user_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_access`
    FOREIGN KEY (`access_id`)
    REFERENCES `schmal`.`access` (`access_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`applicant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`applicant` (
  `applicant_id` BIGINT(20) NOT NULL,
  `prename` MEDIUMTEXT NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `location` MEDIUMTEXT NOT NULL,
  `birth_date` DATE NOT NULL,
  `job_experience_length` INT(11) NOT NULL,
  `applicant_level_id` INT(11) NOT NULL,
  `entered_by_user_id` BIGINT(20) NULL,
  PRIMARY KEY (`applicant_id`, `applicant_level_id`),
  constraint unique applicant_email (email),
  constraint unique applicant_phone_surename (surname, phone),
  CONSTRAINT `applicant_applicant_level`
    FOREIGN KEY (`applicant_level_id`)
    REFERENCES `schmal`.`applicant_level` (`applicant_level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `applicant_user`
    FOREIGN KEY (`entered_by_user_id`)
    REFERENCES `schmal`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`education` (
  `applicant_id` BIGINT(20) NOT NULL,
  `from` DATE NOT NULL,
  `to` DATE NOT NULL,
  `institute` MEDIUMTEXT NOT NULL,
  `field_of_studies` MEDIUMTEXT NULL,
  PRIMARY KEY (`applicant_id`),
  CONSTRAINT `education_applicant`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `schmal`.`applicant` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`job_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`job_experience` (
  `applicant_id` BIGINT(20) NOT NULL,
  `from` DATE NOT NULL,
  `to` DATE NOT NULL,
  `company` MEDIUMTEXT NOT NULL,
  `position` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`applicant_id`),
  CONSTRAINT `job_experience_applicant`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `schmal`.`applicant` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`applicant_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`applicant_status` (
  `applicant_status_id` INT(11) NOT NULL,
  `applicant_status` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`applicant_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`applicant_has_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`applicant_has_status` (
  `applicant_status_id` INT(11) NOT NULL,
  `applicant_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`applicant_status_id`, `applicant_id`),
  INDEX `applicant_id_idx` (`applicant_id` ASC),
  CONSTRAINT `applicant_status_id`
    FOREIGN KEY (`applicant_status_id`)
    REFERENCES `schmal`.`applicant_status` (`applicant_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `applicant_id`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `schmal`.`applicant` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`job_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`job_status` (
  `job_status_id` INT(11) NOT NULL,
  `job_status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`job_status_id`),
  UNIQUE INDEX `job_status_UNIQUE` (`job_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`skill` (
  `skill_id` BIGINT(20) NOT NULL,
  `skill` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`skill_id`),
  UNIQUE INDEX `skill_UNIQUE` (`skill` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`job` (
  `job_id` BIGINT(20) NOT NULL,
  `title` MEDIUMTEXT NOT NULL,
  `job_status_id` INT(11) NOT NULL,
  `skill_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`job_id`, `job_status_id`, `skill_id`),
  INDEX `job_status_id_idx` (`job_status_id` ASC),
  INDEX `skill_id_idx` (`skill_id` ASC),
  CONSTRAINT `job_status_id`
    FOREIGN KEY (`job_status_id`)
    REFERENCES `schmal`.`job_status` (`job_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `skill_id`
    FOREIGN KEY (`skill_id`)
    REFERENCES `schmal`.`skill` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`job_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`job_application` (
  `job_application_id` BIGINT(20) NOT NULL,
  `applicant_id` BIGINT(20) NOT NULL,
  `job_id` BIGINT(20) NOT NULL,
  `salary_expectation` BIGINT(20) NOT NULL,
  `applying_date` DATE NOT NULL,
  PRIMARY KEY (`job_application_id`, `applicant_id`, `job_id`),
  INDEX `application_id_idx` (`applicant_id` ASC),
  INDEX `job_id_idx` (`job_id` ASC),
  CONSTRAINT `job_application_applicant`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `schmal`.`applicant` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_application_job`
    FOREIGN KEY (`job_id`)
    REFERENCES `schmal`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`job_application_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`job_application_attachment` (
  `attachment_id` BIGINT(20) NOT NULL,
  `job_application_id` BIGINT(20) NOT NULL,
  `file` BLOB NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`attachment_id`, `job_application_id`),
  INDEX `applicant_id_idx` (`job_application_id` ASC),
  CONSTRAINT `job_application_attachment_job_application`
    FOREIGN KEY (`job_application_id`)
    REFERENCES `schmal`.`job_application` (`job_application_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`note` (
  `applicant_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `note` MEDIUMTEXT NOT NULL,
  `time` DATE NOT NULL,
  PRIMARY KEY (`applicant_id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `applicant_id_idx` (`applicant_id` ASC),
  CONSTRAINT `note_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `schmal`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `note_applicant`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `schmal`.`applicant` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`applicant_has_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`applicant_has_skills` (
  `applicant_id` BIGINT(20) NOT NULL,
  `skill_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`applicant_id`, `skill_id`),
  INDEX `skill_id_idx` (`skill_id` ASC),
  INDEX `applicant_id_idx` (`applicant_id` ASC),
  CONSTRAINT `applicant_has_skills_skill`
    FOREIGN KEY (`skill_id`)
    REFERENCES `schmal`.`skill` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `applicant_has_skills_applicant`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `schmal`.`applicant` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`communication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`communication` (
  `applicant_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `time` DATE NOT NULL,
  PRIMARY KEY (`applicant_id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `applicant_id_idx` (`applicant_id` ASC),
  CONSTRAINT `communication_applicant`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `schmal`.`applicant` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `communication_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `schmal`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`notification` (
  `user_id` BIGINT(20) NOT NULL,
  `skill_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `skill_id`),
  INDEX `skill_id_idx` (`skill_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `notification_skill`
    FOREIGN KEY (`skill_id`)
    REFERENCES `schmal`.`skill` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notification_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `schmal`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schmal`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schmal`.`rating` (
  `job_application_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `vote` CHAR(1),
  PRIMARY KEY (`job_application_id`, `user_id`),
  INDEX `job_application_id_idx` (`job_application_id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `rating_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `schmal`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rating_job_application`
    FOREIGN KEY (`job_application_id`)
    REFERENCES `schmal`.`job_application` (`job_application_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
